[tool.poetry]
name = "python snippets"
version = "0.1.0"
description = ""
authors = ["José Nunes <josenunesra@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
bokeh = "^3.2.0"
dependency-injector = "^4.41.0"
folium = "^0.14.0"
matplotlib = "^3.7.2"
pydataset = "^0.2.0"
pymongo = "^4.4.1"
scikit-learn = "^1.3.0"
seaborn = "^0.12.2"
dask = "^2023.7.0"
fastparquet = "^2023.7.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.960"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
