[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["José Nunes <josenunesra@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
bokeh = "^2.4.3"
dependency-injector = "^4.39.1"
folium = "^0.12.1"
matplotlib = "^3.5.2"
pydataset = "^0.2.0"
pymongo = "^4.2.0"
scikit-learn = "^1.1.1"
seaborn = "^0.11.2"


[tool.poetry.dev-dependencies]
mypy = "^0.960"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
