version: "3.8"

networks:
  otel:

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - otel

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - otel
  # default user: admin
  # default password: admin

  otel_collector:
    image: otel/opentelemetry-collector
    container_name: otel_collector
    ports:
      - 4317:4317
      - 55679:55679
    networks:
      - otel
    volumes:
      - ./otel-collector-config.yaml:/conf/otel-collector-config.yaml
    command: ["--config=/conf/otel-collector-config.yaml"]

  auto_otel_app:
    image: auto_otel_app:0.1.0
    build: 
      context: .
      dockerfile: Dockerfile.auto_otel
    container_name: fastapi-auto_otel_app
    ports:
      - 8000:8000
    networks:
      - otel
    environment:
      -  OTEL_EXPORTER_OTLP_INSECURE=true
    command: opentelemetry-instrument --exporter_otlp_endpoint otel_collector:4317 --traces_exporter console,otlp --metrics_exporter console,otlp --service_name my-fastapi-app uvicorn auto_otel_app:app --host 0.0.0.0 --port 8000
