FROM python:3.10

WORKDIR /code

RUN pip install \
    --no-cache-dir \
    --upgrade \
    fastapi uvicorn opentelemetry-distro opentelemetry-instrumentation-fastapi opentelemetry-exporter-otlp

COPY ./auto_otel_app.py /code/auto_otel_app.py

CMD opentelemetry-instrument \
    --traces_exporter console,otlp \
    --metrics_exporter console,otlp \
    --service_name my-fastapi-service \
    --exporter_otlp_endpoint 0.0.0.0:4317 \
    uvicorn auto_otel_app:app --host 0.0.0.0 --port 8000
